on: pull_request

jobs:
  default:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      with:
        lfs: true

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: '2.2.10'

    - name: Run nimble test
      run: nimble test
